user:
  name:
    max_len: 50
  email:
    max_len: 255
  password:
    min_len: 6

remember_status:
  is_true: "1"
  is_false: "0"

users_helper:
  size: 80

view_users:
  gravatar_size: 50

ctrl_users:
  num_users_per_page: 30
